"""Core data models for device-use."""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator


class SafetyLevel(str, Enum):
    """Safety enforcement level. Hardware devices default to strict."""

    STRICT = "strict"
    NORMAL = "normal"
    PERMISSIVE = "permissive"


class ActionType(str, Enum):
    """Supported GUI action types."""

    CLICK = "click"
    DOUBLE_CLICK = "double_click"
    RIGHT_CLICK = "right_click"
    TYPE = "type"
    HOTKEY = "hotkey"
    SCROLL = "scroll"
    DRAG = "drag"
    WAIT = "wait"
    SCREENSHOT = "screenshot"
    MOVE = "move"


class ScreenDefinition(BaseModel):
    """Screen/window resolution metadata."""

    width: int = 1920
    height: int = 1080
    scale_factor: float = 1.0

    @field_validator("width", "height")
    @classmethod
    def _positive(cls, v: int) -> int:
        if v <= 0:
            raise ValueError(f"Screen dimension must be > 0, got {v}")
        return v


class UIElement(BaseModel):
    """A known UI element in the instrument software."""

    name: str
    description: str = ""
    region: tuple[int, int, int, int] | None = None  # x, y, w, h
    element_type: str = "button"


class SafetyConstraints(BaseModel):
    """Safety bounds and constraints for a device profile."""

    max_actions_per_minute: int = 30
    forbidden_regions: list[tuple[int, int, int, int]] = Field(default_factory=list)
    requires_confirmation: list[str] = Field(default_factory=list)
    emergency_stop_file: str = "/tmp/device_use_stop"
    bounds: dict[str, Any] = Field(default_factory=dict)


class WorkflowStep(BaseModel):
    """A single step in a predefined workflow."""

    action: ActionType
    target: str = ""
    parameters: dict[str, Any] = Field(default_factory=dict)
    description: str = ""
    verify: str = ""
    requires_confirmation: bool = False


class WorkflowDefinition(BaseModel):
    """A named sequence of steps (procedural memory)."""

    name: str
    description: str = ""
    steps: list[WorkflowStep] = Field(default_factory=list)


class DeviceProfile(BaseModel):
    """Complete profile for an instrument or scientific software.

    The `hardware_connected` flag controls safety enforcement:
    - True (plate reader, microscope): strict 5-layer safety
    - False (FIJI, FlowJo): relaxed, only L1 whitelist enforced
    """

    name: str
    version: str = "1.0"
    description: str = ""
    software: str
    hardware_connected: bool = False
    safety_level: SafetyLevel = SafetyLevel.NORMAL
    screen: ScreenDefinition = Field(default_factory=ScreenDefinition)
    window_title_pattern: str = ""
    ui_elements: list[UIElement] = Field(default_factory=list)
    workflows: list[WorkflowDefinition] = Field(default_factory=list)
    safety: SafetyConstraints = Field(default_factory=SafetyConstraints)
    allowed_actions: list[ActionType] = Field(default_factory=lambda: list(ActionType))
    metadata: dict[str, Any] = Field(default_factory=dict)


class ActionRequest(BaseModel):
    """A requested GUI action (generated by the planner)."""

    action_type: ActionType
    target: str = ""
    parameters: dict[str, Any] = Field(default_factory=dict)
    coordinates: tuple[int, int] | None = None
    description: str = ""


class ActionResult(BaseModel):
    """Result of executing a GUI action."""

    success: bool
    action: ActionRequest
    error: str = ""
    duration_ms: float = 0


class AgentState(BaseModel):
    """Runtime state of the agent loop."""

    step: int = 0
    task: str = ""
    status: str = "idle"  # idle, running, paused, completed, failed
    history: list[dict[str, Any]] = Field(default_factory=list)
    last_action: ActionResult | None = None
